Adding the 6th,7th and 8th precompiles and its tests, with the change…
hyperledger/burrow pull request #1284
Opened 2019-10-05 15:08 UTC by madiazp

…s of the

https://github.com/hyperledger/burrow/pull/1283 PR.

Signed-off-by: matias diaz <matias.dpz@gmail.com>

2019-10-05 15:12 UTC, madiazp commented
Also add some test for the 5,6,7 and 8th precompiles functions. For some reason the 5th one doesn't work with the changes of the #1283 PR. When the #1283 PR get merged I can add a Libsnark proof in the evm_test that will test the 5,6,7 and 8th at once with a real case use.

2019-10-09 20:07 UTC, silasdavis requested changes
Thanks for this Matias!

I think Clearmatics maintains this forked version of bn256 here: https://github.com/clearmatics/bn256. Let's use that as dependency rather than copying in the one from go-ethereum (though as you note there is no licensing issue with that, I'd just prefer to use a somewhat maintained fork).

If you rebase on master you'll get the other changes I have made, then I will give this another review and get it merged.

2019-10-09 20:07 UTC, silasdavis commented on go.mod
> +	github.com/cloudflare/bn256 v0.0.0-20190523220833-828ba4f91854 // indirect
needs to be removed

2019-10-09 20:07 UTC, silasdavis commented on go.mod
> +	github.com/ethereum/go-ethereum v1.9.6
Also needs to be removed :)

2019-10-10 18:59 UTC, madiazp commented
Done ;)

Also fixed a problem with expMod. And added a proof snark test in evm_test.go

Your test of expMod on evm_test failed but the test of it in precompile_test passed and the snark_proof also passed so you may want to check it.

2020-02-21 11:56 UTC, gregdhill commented
@madiazp if you wouldn't mind re-basing this PR, I would be keen to merge this into master!

2020-03-09 00:49 UTC, silasdavis commented
@gregdhill perhaps you could pick up integrating this and maybe some of the other EVM updates we need.

2020-03-19 03:21 UTC, madiazp commented
Uh I don't know why the docker check failed. But again the test of expMod failed, you may want to check that personally. 
Sorry the delay

2021-03-19 17:57 UTC, closed without merging