Added keccak256/ripemd160/sha2-256 system contract for ewasm
hyperledger/burrow pull request #1406
Opened 2020-10-01 21:33 UTC by sxysun

This resolves the issue in the solang repo: https://github.com/hyperledger-labs/solang/issues/268

In ewasm design doc, it writes that the calls to hash functions should be implemented by calls to external contracts (system contracts). But currently, solang uses its own hash function implementation, so we want to add some resolvers to the wasm VM in burrow to support that.

2020-10-02 10:02 UTC, gregdhill approved these changes

2020-10-02 10:04 UTC, gregdhill commented
Please sign the DCO, other test failures are unrelated to this PR. Otherwise, LGTM!

2020-10-02 10:54 UTC, seanyoung commented
@sxysun looks great, thank you.

Please can you remove the .DS_Store and the execution/.DS_Store files; they should not be checked in.

2020-10-02 10:55 UTC, seanyoung requested changes
Please can you remove the .DS_Store and the execution/.DS_Store files; they should not be checked in.

2020-10-02 11:02 UTC, seanyoung commented on execution/wasm/wasm.go
> +			// gas := int(uint64(vm.GetCurrentFrame().Locals[0]))
Ideally the call function should be implemented properly and then the precompiles in https://github.com/hyperledger/burrow/blob/master/execution/native/precompiles.go can be called.

2020-10-09 15:01 UTC, seanyoung commented
@silasdavis to implement proper calls:

Add the lines: https://github.com/hyperledger/burrow/blob/6eaa052f6962f441bf8a469bd1b83026e7708d47/execution/wasm/wasm.go#L77-L88 (you may want to give `address` the type `crypto.Address`).

The call data is in vm.Memory[dataPtr:dataPtr+dataLen]
The call must then be dispatched and the returndata stored in `e.returnData` and the appropriate return code passed on.

That should be all to make external calls work.

Once that is in place, the precompiles can be used for hashing and the code here is no longer needed.

2021-02-01 22:25 UTC, silasdavis commented
This did take a little while for me to come around to, but I have began to implement (really to finish off) cross-engine calls in this PR: https://github.com/hyperledger/burrow/pull/1421

As Sean says once of the things this will allow is for WASM code to call the precompiles (or any of the Go native contracts). Once we have that up and running we can close this in favour of that. Thanks for pointing this out @sxysun

2021-02-01 22:25 UTC, closed without merging