add ecrecover precompile
hyperledger/burrow pull request #1415
Opened 2021-01-18 09:32 UTC by vgrabovski-lacero-platform

signed-off-by: Vitali Grabovski<v.grabovski@lacero.io>

Related to https://github.com/hyperledger/burrow/issues/1240

2021-01-25 20:52 UTC, silasdavis requested changes
Thanks very much, see comments inline if you can respond on thsoe I'd love to get this merged in. 

Can you rebase? I have (finally) fixed the CI

2021-01-25 20:52 UTC, silasdavis commented on execution/native/precompiles_test.go
> +	messageDigest := []byte("21400fb863b0ee7392af02491b6ca5fb87f68ad6af4867b104282dd8fe8b52e4")
Could we have a comment describing how these were generated - even better if we can generate them - we have little embedding utiltity that will compile solidity files and put their bytes and metadata into `.sol.go` files, see: https://github.com/monax/platform/blob/master/Makefile#L297-L299

2021-01-25 20:52 UTC, silasdavis commented on execution/native/precompiles.go
> +	publicKey, isCompressed, err := ecdsa.RecoverCompact(sig, hash)
Please our existing secp256k1-providing dependency `"github.com/btcsuite/btcd/btcec"`: `btcec.RecoverCompact` should do the job.

2021-01-25 20:52 UTC, silasdavis commented on go.mod
> +	github.com/decred/dcrd/dcrec/secp256k1/v3 v3.0.0
Looks like this is a fork of btcsuite secp256k1 - I would like avoid pulling in any new crypto dependencies that would need to be audited.

2021-01-28 19:13 UTC, silasdavis commented
I've rolled this into #1420

2021-01-28 19:13 UTC, closed without merging

2021-02-03 10:43 UTC, vgrabovski-lacero-platform commented
Would like to work on your notes but it seems like you have already done it by yourself @silasdavis

2021-02-03 11:08 UTC, silasdavis commented
Ah hello! Sorry I didn't mean to take if off you if you were still interested in finishing it off. I did base more work off your commit.

When looking into it I realised a few other things were not being done correctly with our handling of secp256k1 outside of ecrecover.

I don't know if you are at all interested in implementing some of the other elliptic curve precompiles. There is an abandoned PR with some of the work here: https://github.com/hyperledger/burrow/pull/1284

If that has any value or interest to you I'd be very pleased to assist with merging a PR

2021-02-03 11:12 UTC, vgrabovski-lacero-platform commented
I don't mind. That is nice that better Burrow version in now in master! Well done

2021-02-03 11:14 UTC, vgrabovski-lacero-platform commented
I will take a look at https://github.com/hyperledger/burrow/pull/1284 This mab be close to feature I would like to be included in Hyperledger_Burrow